### ISSUE TITLE
Installing from an image on a drive?

### ISSUE THREAD

**Issue by etzabo** [AsahiLinux/asahi-installer#135]
I have a USB-C SSD with [this image](https://github.com/Victrid/splatplost/blob/master/docs/image.md) on it. How can I put it on my Mac with Asahi? I need bluetooth support inbuilt.

**Comment by marcan** [comment]
You cannot run x86 images on ARM machines, and Apple Silicon Macs cannot boot directly from USB.

You could instead install Asahi normally, then just run the application instead of trying to use the image, but please do not open issues here for third-party software support. You should ask on their bug tracker if you run into issues instead.
