### ISSUE TITLE
12.5 firmware version missing

### ISSUE THREAD

**Issue by colin-williams** [AsahiLinux/asahi-installer#150]
Installing asahi. During the install it asked me for a firmware version. Gave the options of 12.3 or 12.4 . I had a look at my macOS version, appeared to be 12.5 . So I chose 12.4 . Then I decided to search and found https://asahilinux.org/2022/07/july-2022-release/ . So I think I choose the wrong firmware version. Can I rerun the installer to fix this? Should I be using 12.3 if it looks like 
I am on mac OS 12.5?

**Comment by marcan** [comment]
The prompt is about the firmware version used for Asahi Linux, which has nothing to do with the macOS version you have. Currently supported firmwares are 12.3 for M1 devices and 12.4 for M2 devices. Since you have an M1, you are running an unsupported firmware version. It may or may not work as a consequence of M2 support, but we offer no guarantees.

The prompt is only shown in expert mode, the default option is 12.3, and the prompt explicitly says "If unsure, just press enter". So I'm not entirely sure why you picked 12.4. Either way, there's no bug here.

There is currently no way to switch firmware versions for an existing install. This may be supported in the future. You could wait and see if 12.4 works, or just wipe and reinstall.
