### ISSUE TITLE
[bug] Installer crashed when resizing disk. Log attached

### ISSUE THREAD

**Issue by benjaminwestern** [AsahiLinux/asahi-installer#158]
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/10046280/installer.log)
1. Attempted to install Asahi - followed installer prompts 
2. selected keep 70% of OSX (Leaving ~150GB for Asahi) 
3. Error appeared as per installer log. Just sharing for visibility. 

Continuing to perform my own debugging and will report back if I identify anything of value

**Comment by benjaminwestern** [comment]
1. Attempted to install Asahi - Followed installer prompts (this time chose expert)
2. When prompted, selected keep 60%
3. Everything worked fine this time. 

If you are interested. Verbose Logs attached
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/10046343/installer.log)

**Comment by marcan** [comment]
This is just diskutil failing, but the logs don't contain the process output so we can't do anything about it. The current dev installer has better checks to avoid this, but there is nothing we can really do if it's not just a size bounds issue (which it doesn't sound like from your 70/60 numbers)...

Unfortunately there are apparently many reasons why diskutil resizes can fail on macOS, due to Apple bugs or corruption issues.

**Comment by benjaminwestern** [comment]
No worries at all :) Just thought I would share.

Appreciate all the team's hard work with Linux on M1!
