### ISSUE TITLE
Option to install speakup and espeakup in installer

### ISSUE THREAD

**Issue by aaron-gh** [AsahiLinux/asahi-installer#171]
Hi,
It would be great if there was an option to install and enable the speakup console screen reader, and the espeakup software speach module during install. I understand that speakers currently do not work, but this could be used via the headphone jack after the install is concluded. This would result in at least some accessibility of the installed system for blind nad parcially sighted people.

**Comment by marcan** [comment]
The installer cannot make changes to the installed image, as it is a pre-baked image and macOS cannot read/write ext4 filesystems. I think this kind of feature belongs in more mature upstream distro flows, especially once we come up with a way to invoke upstream distro installers instead of using pre-baked images.

**Comment by marcan** [comment]
We're moving towards more distro support and eventually having options for custom installations using standard distro installers, which would delegate a11y support to standard upstream flows, so there are no plans to implement our own bespoke a11y solution directly in the reference distro images. Let's close this.
