### ISSUE TITLE
Asahi installer should not silently change the default startup disk to Linux (at least not without explicitly showing a warning and instructions on how to get back to macOS)

### ISSUE THREAD

**Issue by rxhfcy** [AsahiLinux/asahi-installer#244]
I strongly believe that this default behavior of the Asahi Linux installer is not user-friendly, especially for inexperienced users: the installer silently changes the default startup disk to Linux for some reason (!), without first warning the user, and does not provide explicit, clear enough instructions on how to later boot back to their existing macOS installation and/or how to change the default back to macOS. This can be _very_ surprising ("help, why has macOS disappeared, did Asahi destroy my macOS installation?") for users who are not already familiar with the Apple Silicon boot process (the majority of people).

Normal Linux users who have previously installed and dual-booted Linux on “normal” x86 Windows computers will probably expect to see a GRUB-like boot loader menu on startup, where the user can select an OS every time when booting their computer. Unfortunately this is not technically possible on Apple Silicon, but this is not something casual new users will automatically understand. Also, some people will very rarely reboot or shut down, so the macOS "data-loss" (data-hiding) issue might only come up several days or weeks later, when the user for the first time reboots their computer after the Asahi installation process, and finds no obvious way to boot back to the now completely "hidden" macOS (!)

Yes, technically savvy users will be able to use search engines to fix the problem or realize that holding down the power button allows you to select an OS at _every_ startup (i.e. that messing with the power button was not just one of the random special actions that had to be performed during the Asahi installation process after shutting down and then mindlessly following the long list of mandatory final installation steps).

### Suggestion: ###

The Asahi Linux installer should at the very least provide a clear warning to the user that the default startup disk will be changed to Linux (!?), explain what that means in practice, and also provide explicit instructions on how to get back to their existing macOS installation

...or even better, offer a clear choice during the installation: should macOS still remain the default OS when booting the computer, or should the default already be changed to Linux, before the new user has any idea how it works and/or what it looks like? IMHO not changing the default from "macOS" should be the default choice, because that would be safer: realistically, not everyone casually testing Asahi for the first time will immediately make Linux their new default OS. This would help ensure that the installation process is transparent and user-friendly for everyone.

If not making Linux the default is technically impossible for some reason (edit: _and_ the default can't be changed back to macOS at a later time during the installation process), at least warn the user etc.

Thanks for considering this! After the "official" distribution is released, there will be many new users who will be even less experienced than some of the previous alpha/beta testers, and I believe some of them will be *extremely* confused (and scared) if the default behavior is not changed and their current macOS installation is silently hidden by default with no explanation.

**Comment by marcan** [comment]
The installer *has* to change the default startup disk to Linux to work. This is required to boot into the paired recoveryOS in One True RecoveryOS mode, which is required to complete step2 of the install. This is a hard platform requirement. We *could* attempt to automate something with `asahi-bless` to switch back on first boot, but I am not comfortable deploying that to literally every user like that, and it would just cause more complaints in the other direction anyway (most Linux users want to continue to use Linux for at least a few boots, if not forever).

Most OS installers do this, the macOS installer certainly does (macOS even changes the boot disk to itself randomly for updates sometimes, which is annoying). UX-wise, it is what is expected by the majority of users.

It's true that inexperienced users can be caught off guard wondering how to go back to macOS. However, the install process *literally instructs users to enter the boot picker* (because it has to). You have to be quite distracted to go through that, then forget and wonder how to switch back to macOS. And if you do end up wondering, a quick Google search will answer the question of how to select an OS on Macs.

Quite frankly, while it would be lovely to inform users about everything explicitly, the install process is already verbose enough for reasons that are hard platform requirements. Adding even more blurb would just cause more users to gloss over and not read anything.

Thus, sorry, but I'm calling this one WONTFIX.

**Comment by marcan** [comment]
That said, there is room for a *post-install* informational panel, and we've discussed adding something to the Plasma first-login wizard thing that is Asahi-specific and could point users to our documentation or raise important points like this. If you are interested in contributing to make that happen (and in general to improving our [docs](https://pagure.io/fedora-asahi/docs-site/)), that would certainly be welcome.

**Comment by rxhfcy** [comment]
> Quite frankly, while it would be lovely to inform users about everything explicitly, the install process is already verbose enough for reasons that are hard platform requirements. Adding even more blurb would just cause more users to gloss over and not read anything

@marcan Thanks for the explanation. Apple certainly doesn’t make your job easy...

> That said, there is room for a _post-install_ informational panel, and we've discussed adding something to the Plasma first-login wizard thing that is Asahi-specific and could point users to our documentation or raise important points like this. If you are interested in contributing to make that happen (and in general to improving our [docs](https://pagure.io/fedora-asahi/docs-site/)), that would certainly be welcome.

It’s great that you’re considering something like that! I would certainly be interested in trying to make a meaningful difference here, but I fear I might lack the necessary skillz (if someone else with more skills wants to step up, please do though!)

Can I ping you separately somehow to discuss what you guys would find acceptable here? What kind of UI, where, etc? Or should I open a separate issue or something? Thanks!
