### ISSUE TITLE
Power management “shutdown” broken by Asahi installer - M2 MB Air

### ISSUE THREAD

**Issue by PaulCharlton** [AsahiLinux/asahi-installer#283]
First observed issue after the installer’s long warning message of “follow these instructions or you may bork your system” …

The gist of those instructions was to shutdown, wait 25 seconds or more, and then hold the power key until boot device menu was presented.

Instead of shutting down, the machine restarted after about 10 seconds.

———-

Ever more, exiting either MacOS or Asahi with “shutdown -h 0”, or the Apple Menu->Shutdown — results only in a restart 10 seconds later.

I imagine that the Power Management Controller got set to some weird state and none of the available software is actually resetting the state to “known good”

**Comment by PaulCharlton** [comment]
Update:  booting into “MacOS <safe mode>” seems to have cleared the primary issue.   Shutdown from the Apple Menu, or from the shutdown command no longer reboots in 5-10 seconds. [both macOS and Asahi]

However, touching any key on the keyboard, touching the trackpad — starts a power-on cycle, as if the computer were not fully shutdown, but in some sort of sleep mode without hibernation.

**Comment by marcan** [comment]
There is approximately no way for the installer itself to be root cause here, since it makes no changes to anything related to power management and uses Apple tools for everything else in the back end. Sounds like a freak macOS bug that just triggered at an unlucky time. If you can reproduce it, please file a Feedback with Apple.
